#!/usr/bin/env python3

import train

t = train.Trainer(kind='Fc_Sig_H60_I3N',
                  basename="experiment",
                  last=None,
                  traincmd="./train",
                  execute=False)
t.alpha = 0.001
#t.batchsize=16
#t.momentum=0.9

train.sched_M200.train(t, 200, 1_000_000)
train.sched_M200.train(t, 200, 1_000_000)
