#!/usr/bin/env python
import sys
import os

opponent = '~/src/backgammon/nets/drc.w'
playoff_cmd = '~/src/backgammon/playoff'
trials = 100_000

def usage():
    print("playoff CSV-file from [to]")
    print("")
    print("  Perform playoffs and append results to CSV file.")
    print("")
    print("  The CSV file need not exist initially.")
    print("")
    print("  The sequences numbers 'from' and 'to' are numbers, and")
    print("  the net files to use are derived from those numbers")
    print("  and the sequence values.")
    print("")
    sys.exit(-1)

def playoff(csv, player, opponent):
    cmd = f'{playoff_cmd} -e 1000 -n {trials} {player} {opponent} 2>>{csv}'
    print(cmd)
    r = os.system(cmd)

    if r & 0xff:
        print("aborted\n");
        sys.exit(1)

    if r:
        print("error encountered, exiting\n");
        sys.exit(1)


def playoffs(csv, bname, start, stop):
    if os.path.isfile(csv) == False:
        os.system(f'echo white,black,trials,equity,sw,sl,gw,gl,bw,bl >>{csv}')

    for i in range(start, stop+1):
        player = f'{bname}-{i}.w'
        playoff(csv, player, opponent)


def main(args):
    n = len(args)
    if n < 3 or n > 4:
        usage()

    csv = args[1]
    bname = os.path.splitext(csv)[0]
    start = int(args[2])
    if n == 4:
        stop = int(args[3])
    else:
        stop = start
        
    playoffs(csv, bname, start, stop)

main(sys.argv)

